<?php   
$this->headLink()->appendStylesheet($this->basePath('css/blog.css'));                     
$this->headScript()->appendFile($this->basePath('/js/ckeditor/ckeditor.js'));
$title = 'Administration';
$pageTitle = 'Edit Post';
$this->headTitle($title);
$form = $this->form;
?>

<div class="page-header">
	<div class="header">
		<h1><?php echo $this->escapeHtml($title) ?> : <?php echo $this->escapeHtml($pageTitle) ?></h1>
    </div>
</div>

<?php $form->prepare(); ?>
<div class="row">
    <div class="col-lg-12">	
		<div class="col-md-12" id="content">
				
			<div class="panel panel-default object-panel">
				<br>
				<div class="panel-body" id="box">							
					<?php 			
						echo $this->form()->openTag($form);
						echo $this->formCollection($form);
						echo $this->form()->closeTag();
					?>	
				</div>
			</div>
			
		</div>
	</div>		
</div> 
<script>
	CKEDITOR.replace( 'textarea' );
</script>
