<?php
//$this->inlineScript()->appendFile($this->basePath('/js/register.js'));
$post = $this->post;
$title = 'Blog';
$postTitle = $post->getTitle();
$this->headTitle($title . ' - ' . $postTitle);
//$form = $this->form;
?>

<div class="page-header">
	<div class="header">
		<h1><?php echo $this->escapeHtml($title) ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">	

		<div class="col-md-12" id="content">
			<div class="panel panel-default object-panel">
				
				<div class="panel-body">								
					<div>
						<h1><?php echo $this->escapeHtml($postTitle) ?></h1>
						<p>by <a href="#"><?php// echo $post->user->username; ?></a> At
							<span class=".pull-right"></span> <?php echo $post->getPostedAt(); ?></p>
					</div>	
					<hr>																			
					<div><p><?php echo $this->htmlPurifier($post->getContent());?></p></div>
					<hr>
					
					<div class="categorie-labels">
						<?php foreach ($post->getUserArticles() as $cat): ?>
							 <span class="label label-default"><?php echo $cat->category->title; ?></span>
						<?php endforeach; ?>
					</div>	
																									
				</div>
			</div>								
		</div> 									
	</div>	
</div>

		
