<?php
$title = 'Administration';
$pageTitle = 'Add Category';
$this->headTitle($title);
$form = $this->form;
//$form->setAttribute('action', $this->url('category', array('action' => 'add', 'id' => $this->id)));
?>

<div class="page-header">
	<div class="header">
		<h1><?php echo $this->escapeHtml($title) ?></h1>
    </div>
</div>

<?php $form->prepare(); ?>
<div class="row">
    <div class="col-lg-12">	
		<div class="col-md-12" id="content">
				
			<div class="panel panel-default object-panel">
				<div class="panel-body">
					<h2 class=""><?php echo $this->escapeHtml($pageTitle) ?></h2>
				</div>
				<div class="panel-post" id="box">							
					<?php 			
						echo $this->form()->openTag($form);
						echo $this->formCollection($form);
						echo $this->form()->closeTag();
					?>	
				</div>
			</div>
			
		</div>
	</div>		
</div> 
