<?php
$title = 'Categories';
$this->headTitle($title);
?>
<div class="page-header">
	<div class="header">
		<h1><?php echo $this->escapeHtml($title) ?></h1>
    </div>
</div>
	
<div class="row">

    <div class="col-lg-12">
		<div class="col-md-12" id="content">
			<div class="panel panel-default object-panel">	
				<div class="panel-body">
					<a href="<?php echo $this->url('category', array('action' => 'add')); ?>">Add Category</a> || <a href="<?php echo $this->url('tiny-blog'); ?>">Articles</a>					
				</div>
			</div>																	
			<div class="panel panel-default object-panel">	
				<div class="panel-body">											
					<table class="table table-striped table-hover table-bordered" id="post-list">							
						<thead>
							<tr>
								<th>Id</th>								
								<th>Category Title</th>
								<th>Edit</th>
							</tr>
						</thead>
						<tbody>
					<?php foreach ($categories as $category): ?>
							<tr>
								<td><?php echo $this->escapeHtml($category->id); ?></td>								
								<td><?php echo $this->escapeHtml($category->title); ?></td>
								<td>
									<a href="<?php echo $this->url('category', array(
										'action' => 'delete', 'id' => $category->id)) ?>"><span>Delete</span> 
									</a> ||
									<a href="<?php echo $this->url('category', array(
											'action' => 'edit', 'id' => $category->id)) ?>"><span>Edit</span> 
									</a>				
								</td>
							</tr>
					<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
			
		</div>
	</div>
</div>
